name: Terraform Workflow
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: apply or destroy'
        required: true
        default: 'apply'
      dashboard_name:
        description: 'Name of the dashboard to delete (only required for destroy action)'
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform plan

      - name: Terraform Apply - Auto-Approve
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform Plan Destroy
        if: ${{ github.event.inputs.action == 'destroy' && github.event.inputs.dashboard_name != '' }}
        run: terraform plan -destroy -target="newrelic_dashboard.${{ github.event.inputs.dashboard_name }}"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' && github.event.inputs.dashboard_name != '' }}
        run: terraform destroy -auto-approve -target="newrelic_dashboard.${{ github.event.inputs.dashboard_name }}"
