name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Apply - Auto-Approve
        run: terraform apply -auto-approve

  terraform_destroy:
    runs-on: ubuntu-latest
    needs: [terraform_apply]  # Wait for terraform_apply job to finish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy - Auto-Approve
        run: terraform destroy -auto-approve
